### Data Preparation

#### Import libraries

In [1]:
import pandas as pd
import numpy as np

#### Import data

In [2]:
#preserve indexes for correct matching
loan_data_inputs_train = pd.read_csv('loan_data_inputs_train.csv', index_col = 0) #use content of the first column as indexes
# loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0, header = None) #don't import header for the df with targets
loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0)
loan_data_inputs_test = pd.read_csv('loan_data_inputs_test.csv', index_col = 0)
loan_data_target_test = pd.read_csv('loan_data_targets_test.csv', index_col = 0)

In [3]:
# Here we import the new data.
loan_data_backup = pd.read_csv('loan_data_2015.csv')

C:\Users\lkima\AppData\Local\Temp\ipykernel_18336\3437895857.py:2: DtypeWarning: Columns (19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  loan_data_backup = pd.read_csv('loan_data_2015.csv')

#### Explore data

In [4]:
loan_data = loan_data_backup.copy()

In [5]:
pd.options.display.max_columns = None
#pd.options.display.max_rows = None
# Sets the pandas dataframe options to display all columns/ rows.

In [6]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m
0,68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,10+ years,MORTGAGE,128000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,200xx,DC,6.46,0.0,Feb-90,0.0,46.0,NaN,17.0,0.0,14277,27.4,46.0,w,35000.0,35000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,56.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,321.0,146867.0,1.0,11.0,0.0,0.0,28.0,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0
1,68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,< 1 year,MORTGAGE,100000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,462xx,IN,7.28,0.0,Jul-01,0.0,NaN,NaN,15.0,0.0,7158,26.7,24.0,w,8650.0,8650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,165450.0,0.0,1.0,1.0,1.0,11.0,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0
2,67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,5 years,RENT,35000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,672xx,KS,15.22,2.0,Jul-11,0.0,18.0,NaN,6.0,0.0,1058,24.6,6.0,w,4225.0,4225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4888.0,0.0,1.0,0.0,0.0,47.0,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0
3,68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0.0,Dec-98,1.0,NaN,NaN,10.0,0.0,5812,40.9,23.0,w,10000.0,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,41166.0,1.0,3.0,0.0,2.0,13.0,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0
4,68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-00,0.0,NaN,NaN,6.0,0.0,7869,56.2,18.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Dec-15,0.0,NaN,1,JOINT,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0

In [7]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 74 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
dtypes: float64(45), int64(6), object(23)
memory usage: 237.7+ MB

### Genral preprocessing

#### Preprocessing continous variables

In [10]:
#display values that a column takes
loan_data['emp_length'].unique()

array(['10+ years', '< 1 year', '5 years', '3 years', '4 years', nan,
       '2 years', '8 years', '9 years', '1 year', '6 years', '7 years'],
      dtype=object)

In [11]:
#str.replace (<string to be replaced>, <new replacement string>)  - finds a string inside of another string and if found replace first string with given new string , if the first string is replaced with nothing it will be deleted from the given string
loan_data['emp_length_int'] = loan_data['emp_length'].str.replace(r'\+', ' ', regex=True)
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('< 1 year', str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace('n/a',  str(0))
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' years', '')
loan_data['emp_length_int'] = loan_data['emp_length_int'].str.replace(' year', '')
# We store the preprocessed ‘employment length’ variable in a new variable called ‘employment length int’,
# We assign the new ‘employment length int’ to be equal to the ‘employment length’ variable with the string ‘+ years’
# replaced with nothing. Next, we replace the whole string ‘less than 1 year’ with the string ‘0’.
# Then, we replace the ‘n/a’ string with the string ‘0’. Then, we replace the string ‘space years’ with nothing.
# Finally, we replace the string ‘space year’ with nothing.

In [12]:
#check data type of a single element with the 0 index
type(loan_data['emp_length_int'][0])

str

In [13]:
#transfomr it to numeric column
loan_data['emp_length_int'] = pd.to_numeric(loan_data['emp_length_int'])

In [14]:
#check dat type
type(loan_data['emp_length_int'][0])

numpy.float64

In [15]:
loan_data['term'].unique()

array([' 60 months', ' 36 months'], dtype=object)

In [16]:
loan_data['term_int'] = loan_data['term'].str.replace(' months','')

In [17]:
type(loan_data['term_int'][0])

str

In [18]:
loan_data['term_int'] = pd.to_numeric(loan_data['term_int'])

In [19]:
type(loan_data['term_int'][0])

numpy.int64

In [20]:
loan_data['earliest_cr_line']

0         Feb-90
1         Jul-01
2         Jul-11
3         Dec-98
4         Aug-00
           ...
421089    Sep-04
421090    Mar-74
421091    Sep-03
421092    Oct-03
421093    Dec-01
Name: earliest_cr_line, Length: 421094, dtype: object

In [21]:
# #convert the earliest cr line to date
# loan_data['earliest_cr_line_date'] = pd.to_datetime(
#     loan_data['earliest_cr_line'], 
#     format='%b-%y'
# )

In [22]:
loan_data['earliest_cr_line_date'] = pd.to_datetime(
    loan_data['earliest_cr_line'],
    format='%b-%y'
)

loan_data['earliest_cr_line_date'] = loan_data['earliest_cr_line_date'].apply(
    lambda x: x if x.year <= 2017 else x.replace(year=x.year - 100)
)

In [23]:
loan_data['earliest_cr_line_date'].sample()

322790   1994-11-01
Name: earliest_cr_line_date, dtype: datetime64[ns]

In [24]:
#check type of one of the records in that column - first record
type(loan_data['earliest_cr_line_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [25]:
#check how many months/days past referencing a specific start date
# 1. Create the reference date object
ref_date = pd.to_datetime('2017-12-01')

In [26]:
# 2. Subtract the column from the reference date
loan_data['days_since_earliest_cr_line'] = ref_date - loan_data['earliest_cr_line_date']

In [27]:
loan_data['days_since_earliest_cr_line']

0        10165 days
1         5997 days
2         2345 days
3         6940 days
4         6331 days
            ...
421089    4839 days
421090   15981 days
421091    5205 days
421092    5175 days
421093    5844 days
Name: days_since_earliest_cr_line, Length: 421094, dtype: timedelta64[ns]

In [28]:
print(loan_data['days_since_earliest_cr_line'].min())

1856 days 00:00:00

In [29]:
# 2. Extract the number of days (.dt.days)
# 3. Divide by 30.44 and round to convert to months
loan_data['mths_since_earliest_cr_line'] = np.round(loan_data['days_since_earliest_cr_line'].dt.days / 30.44).astype('Int64')

In [30]:
print(loan_data['mths_since_earliest_cr_line'].head())

0    334
1    197
2     77
3    228
4    208
Name: mths_since_earliest_cr_line, dtype: Int64

In [31]:
loan_data['mths_since_earliest_cr_line'].describe()

count      421094.0
mean     230.586458
std       91.329014
min            61.0
25%           168.0
50%           212.0
75%           278.0
max           887.0
Name: mths_since_earliest_cr_line, dtype: Float64

In [32]:
#select specific rows and columns by their labels using loc and enclose the column names in brackets again to output a list 
loan_data.loc[: , ['earliest_cr_line', 'earliest_cr_line_date', 'mths_since_earliest_cr_line']][loan_data['mths_since_earliest_cr_line']<0]

Empty DataFrame
Columns: [earliest_cr_line, earliest_cr_line_date, mths_since_earliest_cr_line]
Index: []

In [33]:
loan_data.loc[loan_data['mths_since_earliest_cr_line'] < 0, 'mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].max()

In [34]:
loan_data['mths_since_earliest_cr_line'].unique()

<IntegerArray>
[334, 197,  77, 228, 208, 193, 192, 172, 362, 296,
 ...
 686, 797, 808, 748, 702, 716, 673, 767, 803, 887]
Length: 668, dtype: Int64

In [35]:
print(loan_data['mths_since_earliest_cr_line'].min())

61

In [36]:
loan_data.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'term_int', 'earliest_cr_line_date',
       'days_since_earliest_cr_line', 'mths_since_earliest_cr_line'],
      dtype='object')

In [37]:
loan_data['issue_d']

0         Dec-15
1         Dec-15
2         Dec-15
3         Dec-15
4         Dec-15
           ...
421089    Jan-15
421090    Jan-15
421091    Jan-15
421092    Jan-15
421093    Jan-15
Name: issue_d, Length: 421094, dtype: object

In [38]:
loan_data['issue_d_date'] = pd.to_datetime(loan_data['issue_d'], format = '%b-%y')

In [39]:
loan_data['issue_d_date'].head()

0   2015-12-01
1   2015-12-01
2   2015-12-01
3   2015-12-01
4   2015-12-01
Name: issue_d_date, dtype: datetime64[ns]

In [40]:
type(loan_data['issue_d_date'][0])

pandas._libs.tslibs.timestamps.Timestamp

In [41]:
issue_d_ref_date = '2017-12-01'
loan_data['days_since_issue_d'] = ref_date - loan_data['issue_d_date']

In [42]:
loan_data['mths_since_issue_d'] = np.round(loan_data['days_since_issue_d'].dt.days / 30.44).astype('Int64')

In [43]:
loan_data['mths_since_issue_d'].head()

0    24
1    24
2    24
3    24
4    24
Name: mths_since_issue_d, dtype: Int64

In [44]:
loan_data['mths_since_issue_d'].describe()

count     421094.0
mean     29.044629
std       3.458162
min           24.0
25%           26.0
50%           29.0
75%           32.0
max           35.0
Name: mths_since_issue_d, dtype: Float64

In [45]:
print(loan_data['mths_since_issue_d'].min())

24

In [46]:
loan_data.columns

Index(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'annual_inc', 'verification_status',
       'issue_d', 'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose',
       'title', 'zip_code', 'addr_state', 'dti', 'delinq_2yrs',
       'earliest_cr_line', 'inq_last_6mths', 'mths_since_last_delinq',
       'mths_since_last_record', 'open_acc', 'pub_rec', 'revol_bal',
       'revol_util', 'total_acc', 'initial_list_status', 'out_prncp',
       'out_prncp_inv', 'total_pymnt', 'total_pymnt_inv', 'total_rec_prncp',
       'total_rec_int', 'total_rec_late_fee', 'recoveries',
       'collection_recovery_fee', 'last_pymnt_d', 'last_pymnt_amnt',
       'next_pymnt_d', 'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m', 'max_bal_bc',
       'all_util', 'total_rev_hi_lim', 'inq_fi', 'total_cu_tl', 'inq_last_12m',
       'emp_length_int', 'term_int', 'earliest_cr_line_date',
       'days_since_earliest_cr_line', 'mths_since_earliest_cr_line',
       'issue_d_date', 'days_since_issue_d', 'mths_since_issue_d'],
      dtype='object')

In [47]:
loan_data.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,term_int,earliest_cr_line_date,days_since_earliest_cr_line,mths_since_earliest_cr_line,issue_d_date,days_since_issue_d,mths_since_issue_d
0,68444620,73334399,35000,35000,35000.0,60 months,11.99,778.38,C,C1,Foreign Service Officer,10+ years,MORTGAGE,128000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,Home improvement,200xx,DC,6.46,0.0,Feb-90,0.0,46.0,NaN,17.0,0.0,14277,27.4,46.0,w,35000.0,35000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,56.0,1,INDIVIDUAL,NaN,NaN,NaN,0.0,321.0,146867.0,1.0,11.0,0.0,0.0,28.0,35367.0,49.3,0.0,1.0,5020.0,40.1,52200.0,1.0,4.0,0.0,10.0,60,1990-02-01,10165 days,334,2015-12-01,731 days,24
1,68547583,73437441,8650,8650,8650.0,36 months,5.32,260.50,A,A1,Associate Consultant,< 1 year,MORTGAGE,100000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,credit_card,Credit card refinancing,462xx,IN,7.28,0.0,Jul-01,0.0,NaN,NaN,15.0,0.0,7158,26.7,24.0,w,8650.0,8650.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,165450.0,0.0,1.0,1.0,1.0,11.0,24041.0,88.8,0.0,3.0,3081.0,57.9,26800.0,1.0,0.0,5.0,0.0,36,2001-07-01,5997 days,197,2015-12-01,731 days,24
2,67849662,72708407,4225,4225,4225.0,36 months,14.85,146.16,C,C5,mechanic,5 years,RENT,35000.0,Source Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,672xx,KS,15.22,2.0,Jul-11,0.0,18.0,NaN,6.0,0.0,1058,24.6,6.0,w,4225.0,4225.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,4888.0,0.0,1.0,0.0,0.0,47.0,3830.0,21.9,0.0,0.0,367.0,22.4,4300.0,0.0,0.0,0.0,5.0,36,2011-07-01,2345 days,77,2015-12-01,731 days,24
3,68506885,73396712,10000,10000,10000.0,60 months,11.99,222.40,C,C1,CARDIOVASCULAR TECH,10+ years,RENT,42500.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,debt_consolidation,Debt consolidation,460xx,IN,31.04,0.0,Dec-98,1.0,NaN,NaN,10.0,0.0,5812,40.9,23.0,w,10000.0,10000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Jan-16,0.0,NaN,1,INDIVIDUAL,NaN,NaN,NaN,0.0,0.0,41166.0,1.0,3.0,0.0,2.0,13.0,35354.0,75.5,1.0,1.0,3118.0,67.4,14200.0,1.0,1.0,1.0,10.0,60,1998-12-01,6940 days,228,2015-12-01,731 days,24
4,68341763,72928789,20000,20000,20000.0,60 months,10.78,432.66,B,B4,truck driver,10+ years,MORTGAGE,63000.0,Not Verified,Dec-15,Issued,n,https://www.lendingclub.com/browse/loanDetail....,NaN,home_improvement,NaN,605xx,IL,10.78,0.0,Aug-00,0.0,NaN,NaN,6.0,0.0,7869,56.2,18.0,w,20000.0,20000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,Jan-16,Dec-15,0.0,NaN,1,JOINT,71000.0,13.85,Not Verified,0.0,0.0,189699.0,0.0,1.0,0.0,4.0,19.0,10827.0,72.8,0.0,2.0,2081.0,64.7,14000.0,2.0,5.0,1.0,10.0,60,2000-08-01,6331 days,208,2015-12-01,731 days,24

#### Preprocessing Discrete variables

##### Creating dummy variables (one-hot encoding)

In [48]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421094 entries, 0 to 421093
Data columns (total 82 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   id                           421094 non-null  int64
 1   member_id                    421094 non-null  int64
 2   loan_amnt                    421094 non-null  int64
 3   funded_amnt                  421094 non-null  int64
 4   funded_amnt_inv              421094 non-null  float64
 5   term                         421094 non-null  object
 6   int_rate                     421094 non-null  float64
 7   installment                  421094 non-null  float64
 8   grade                        421094 non-null  object
 9   sub_grade                    421094 non-null  object
 10  emp_title                    397220 non-null  object
 11  emp_length                   397277 non-null  object
 12  home_ownership               421094 non-null  object
 13  annual_inc                   421094 non-null  float64
 14  verification_status          421094 non-null  object
 15  issue_d                      421094 non-null  object
 16  loan_status                  421094 non-null  object
 17  pymnt_plan                   421094 non-null  object
 18  url                          421094 non-null  object
 19  desc                         45 non-null      object
 20  purpose                      421094 non-null  object
 21  title                        420962 non-null  object
 22  zip_code                     421094 non-null  object
 23  addr_state                   421094 non-null  object
 24  dti                          421094 non-null  float64
 25  delinq_2yrs                  421094 non-null  float64
 26  earliest_cr_line             421094 non-null  object
 27  inq_last_6mths               421094 non-null  float64
 28  mths_since_last_delinq       217133 non-null  float64
 29  mths_since_last_record       74415 non-null   float64
 30  open_acc                     421094 non-null  float64
 31  pub_rec                      421094 non-null  float64
 32  revol_bal                    421094 non-null  int64
 33  revol_util                   420932 non-null  float64
 34  total_acc                    421094 non-null  float64
 35  initial_list_status          421094 non-null  object
 36  out_prncp                    421094 non-null  float64
 37  out_prncp_inv                421094 non-null  float64
 38  total_pymnt                  421094 non-null  float64
 39  total_pymnt_inv              421094 non-null  float64
 40  total_rec_prncp              421094 non-null  float64
 41  total_rec_int                421094 non-null  float64
 42  total_rec_late_fee           421094 non-null  float64
 43  recoveries                   421094 non-null  float64
 44  collection_recovery_fee      421094 non-null  float64
 45  last_pymnt_d                 403811 non-null  object
 46  last_pymnt_amnt              421094 non-null  float64
 47  next_pymnt_d                 395337 non-null  object
 48  last_credit_pull_d           421083 non-null  object
 49  collections_12_mths_ex_med   421094 non-null  float64
 50  mths_since_last_major_derog  122729 non-null  float64
 51  policy_code                  421094 non-null  int64
 52  application_type             421094 non-null  object
 53  annual_inc_joint             511 non-null     float64
 54  dti_joint                    509 non-null     float64
 55  verification_status_joint    511 non-null     object
 56  acc_now_delinq               421094 non-null  float64
 57  tot_coll_amt                 421094 non-null  float64
 58  tot_cur_bal                  421094 non-null  float64
 59  open_acc_6m                  21372 non-null   float64
 60  open_il_6m                   21372 non-null   float64
 61  open_il_12m                  21372 non-null   float64
 62  open_il_24m                  21372 non-null   float64
 63  mths_since_rcnt_il           20810 non-null   float64
 64  total_bal_il                 21372 non-null   float64
 65  il_util                      18617 non-null   float64
 66  open_rv_12m                  21372 non-null   float64
 67  open_rv_24m                  21372 non-null   float64
 68  max_bal_bc                   21372 non-null   float64
 69  all_util                     21372 non-null   float64
 70  total_rev_hi_lim             421094 non-null  float64
 71  inq_fi                       21372 non-null   float64
 72  total_cu_tl                  21372 non-null   float64
 73  inq_last_12m                 21372 non-null   float64
 74  emp_length_int               397277 non-null  float64
 75  term_int                     421094 non-null  int64
 76  earliest_cr_line_date        421094 non-null  datetime64[ns]
 77  days_since_earliest_cr_line  421094 non-null  timedelta64[ns]
 78  mths_since_earliest_cr_line  421094 non-null  Int64
 79  issue_d_date                 421094 non-null  datetime64[ns]
 80  days_since_issue_d           421094 non-null  timedelta64[ns]
 81  mths_since_issue_d           421094 non-null  Int64
dtypes: Int64(2), datetime64[ns](2), float64(46), int64(7), object(23), timedelta64[ns](2)
memory usage: 264.2+ MB

In [49]:
# Create dummy variables for categorical var - K-1 dummy var to represent the info about k categories
# pd.get_dummies(loan_data['grade'])
pd.get_dummies(loan_data['grade'], dtype=int)

        A  B  C  D  E  F  G
0       0  0  1  0  0  0  0
1       1  0  0  0  0  0  0
2       0  0  1  0  0  0  0
3       0  0  1  0  0  0  0
4       0  1  0  0  0  0  0
...    .. .. .. .. .. .. ..
421089  0  1  0  0  0  0  0
421090  0  1  0  0  0  0  0
421091  0  0  0  1  0  0  0
421092  0  0  0  0  1  0  0
421093  0  1  0  0  0  0  0

[421094 rows x 7 columns]

In [50]:
pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ' : ', dtype= int)

,grade : A,grade : B,grade : C,grade : D,grade : E,grade : F,grade : G
0,0,0,1,0,0,0,0
1,1,0,0,0,0,0,0
2,0,0,1,0,0,0,0
3,0,0,1,0,0,0,0
4,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...
421089,0,1,0,0,0,0,0
421090,0,1,0,0,0,0,0
421091,0,0,0,1,0,0,0
421092,0,0,0,0,1,0,0
421093,0,1,0,0,0,0,0

In [51]:
loan_data_dummies = [pd.get_dummies(loan_data['grade'], prefix = 'grade', prefix_sep = ' : ', dtype=int),
                    pd.get_dummies(loan_data['sub_grade'], prefix = 'sub_grade', prefix_sep = ' : ', dtype=int),
                    pd.get_dummies(loan_data['home_ownership'], prefix = 'home_ownership', prefix_sep = ' : ',dtype=int),
                    pd.get_dummies(loan_data['verification_status'], prefix = 'verification_status', prefix_sep = ' : ',dtype=int),
                    pd.get_dummies(loan_data['loan_status'], prefix = 'loan_status', prefix_sep = ' : ',dtype=int),
                    pd.get_dummies(loan_data['purpose'], prefix = 'purpose', prefix_sep = ' : ', dtype=int),
                    pd.get_dummies(loan_data['addr_state'], prefix = 'addr_state', prefix_sep = ' : ',dtype=int),
                    pd.get_dummies(loan_data['initial_list_status'], prefix = 'initial_list_status', prefix_sep = ' : ',dtype=int)]

In [52]:
#make it a df
loan_data_dummies = pd.concat(loan_data_dummies, axis =1)

In [53]:
type(loan_data_dummies)

pandas.core.frame.DataFrame

In [54]:
#combine dummies to original df by rows axis = 0 or columns axis = 1
loan_data = pd.concat([loan_data, loan_data_dummies], axis = 1)

In [55]:
loan_data.columns.values

array(['id', 'member_id', 'loan_amnt', 'funded_amnt', 'funded_amnt_inv',
       'term', 'int_rate', 'installment', 'grade', 'sub_grade',
       'emp_title', 'emp_length', 'home_ownership', 'annual_inc',
       'verification_status', 'issue_d', 'loan_status', 'pymnt_plan',
       'url', 'desc', 'purpose', 'title', 'zip_code', 'addr_state', 'dti',
       'delinq_2yrs', 'earliest_cr_line', 'inq_last_6mths',
       'mths_since_last_delinq', 'mths_since_last_record', 'open_acc',
       'pub_rec', 'revol_bal', 'revol_util', 'total_acc',
       'initial_list_status', 'out_prncp', 'out_prncp_inv', 'total_pymnt',
       'total_pymnt_inv', 'total_rec_prncp', 'total_rec_int',
       'total_rec_late_fee', 'recoveries', 'collection_recovery_fee',
       'last_pymnt_d', 'last_pymnt_amnt', 'next_pymnt_d',
       'last_credit_pull_d', 'collections_12_mths_ex_med',
       'mths_since_last_major_derog', 'policy_code', 'application_type',
       'annual_inc_joint', 'dti_joint', 'verification_status_joint',
       'acc_now_delinq', 'tot_coll_amt', 'tot_cur_bal', 'open_acc_6m',
       'open_il_6m', 'open_il_12m', 'open_il_24m', 'mths_since_rcnt_il',
       'total_bal_il', 'il_util', 'open_rv_12m', 'open_rv_24m',
       'max_bal_bc', 'all_util', 'total_rev_hi_lim', 'inq_fi',
       'total_cu_tl', 'inq_last_12m', 'emp_length_int', 'term_int',
       'earliest_cr_line_date', 'days_since_earliest_cr_line',
       'mths_since_earliest_cr_line', 'issue_d_date',
       'days_since_issue_d', 'mths_since_issue_d', 'grade : A',
       'grade : B', 'grade : C', 'grade : D', 'grade : E', 'grade : F',
       'grade : G', 'sub_grade : A1', 'sub_grade : A2', 'sub_grade : A3',
       'sub_grade : A4', 'sub_grade : A5', 'sub_grade : B1',
       'sub_grade : B2', 'sub_grade : B3', 'sub_grade : B4',
       'sub_grade : B5', 'sub_grade : C1', 'sub_grade : C2',
       'sub_grade : C3', 'sub_grade : C4', 'sub_grade : C5',
       'sub_grade : D1', 'sub_grade : D2', 'sub_grade : D3',
       'sub_grade : D4', 'sub_grade : D5', 'sub_grade : E1',
       'sub_grade : E2', 'sub_grade : E3', 'sub_grade : E4',
       'sub_grade : E5', 'sub_grade : F1', 'sub_grade : F2',
       'sub_grade : F3', 'sub_grade : F4', 'sub_grade : F5',
       'sub_grade : G1', 'sub_grade : G2', 'sub_grade : G3',
       'sub_grade : G4', 'sub_grade : G5', 'home_ownership : ANY',
       'home_ownership : MORTGAGE', 'home_ownership : OWN',
       'home_ownership : RENT', 'verification_status : Not Verified',
       'verification_status : Source Verified',
       'verification_status : Verified', 'loan_status : Charged Off',
       'loan_status : Current', 'loan_status : Default',
       'loan_status : Fully Paid', 'loan_status : In Grace Period',
       'loan_status : Issued', 'loan_status : Late (16-30 days)',
       'loan_status : Late (31-120 days)', 'purpose : car',
       'purpose : credit_card', 'purpose : debt_consolidation',
       'purpose : educational', 'purpose : home_improvement',
       'purpose : house', 'purpose : major_purchase', 'purpose : medical',
       'purpose : moving', 'purpose : other',
       'purpose : renewable_energy', 'purpose : small_business',
       'purpose : vacation', 'purpose : wedding', 'addr_state : AK',
       'addr_state : AL', 'addr_state : AR', 'addr_state : AZ',
       'addr_state : CA', 'addr_state : CO', 'addr_state : CT',
       'addr_state : DC', 'addr_state : DE', 'addr_state : FL',
       'addr_state : GA', 'addr_state : HI', 'addr_state : IL',
       'addr_state : IN', 'addr_state : KS', 'addr_state : KY',
       'addr_state : LA', 'addr_state : MA', 'addr_state : MD',
       'addr_state : ME', 'addr_state : MI', 'addr_state : MN',
       'addr_state : MO', 'addr_state : MS', 'addr_state : MT',
       'addr_state : NC', 'addr_state : ND', 'addr_state : NE',
       'addr_state : NH', 'addr_state : NJ', 'addr_state : NM',
       'addr_state : NV', 'addr_state : NY', 'addr_state : OH',
       'addr_state : OK', 'addr_state : OR', 'addr_state : PA',
       'addr_state : RI', 'addr_state : SC', 'addr_state : SD',
       'addr_state : TN', 'addr_state : TX', 'addr_state : UT',
       'addr_state : VA', 'addr_state : VT', 'addr_state : WA',
       'addr_state : WI', 'addr_state : WV', 'addr_state : WY',
       'initial_list_status : f', 'initial_list_status : w'], dtype=object)

##### Checking and cleaning missing values

In [56]:
#returns true if theres a missing value else false
loan_data.isnull()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,emp_title,emp_length,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,url,desc,purpose,title,zip_code,addr_state,dti,delinq_2yrs,earliest_cr_line,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,open_acc,pub_rec,revol_bal,revol_util,total_acc,initial_list_status,out_prncp,out_prncp_inv,total_pymnt,total_pymnt_inv,total_rec_prncp,total_rec_int,total_rec_late_fee,recoveries,collection_recovery_fee,last_pymnt_d,last_pymnt_amnt,next_pymnt_d,last_credit_pull_d,collections_12_mths_ex_med,mths_since_last_major_derog,policy_code,application_type,annual_inc_joint,dti_joint,verification_status_joint,acc_now_delinq,tot_coll_amt,tot_cur_bal,open_acc_6m,open_il_6m,open_il_12m,open_il_24m,mths_since_rcnt_il,total_bal_il,il_util,open_rv_12m,open_rv_24m,max_bal_bc,all_util,total_rev_hi_lim,inq_fi,total_cu_tl,inq_last_12m,emp_length_int,term_int,earliest_cr_line_date,days_since_earliest_cr_line,mths_since_earliest_cr_line,issue_d_date,days_since_issue_d,mths_since_issue_d,grade : A,grade : B,grade : C,grade : D,grade : E,grade : F,grade : G,sub_grade : A1,sub_grade : A2,sub_grade : A3,sub_grade : A4,sub_grade : A5,sub_grade : B1,sub_grade : B2,sub_grade : B3,sub_grade : B4,sub_grade : B5,sub_grade : C1,sub_grade : C2,sub_grade : C3,sub_grade : C4,sub_grade : C5,sub_grade : D1,sub_grade : D2,sub_grade : D3,sub_grade : D4,sub_grade : D5,sub_grade : E1,sub_grade : E2,sub_grade : E3,sub_grade : E4,sub_grade : E5,sub_grade : F1,sub_grade : F2,sub_grade : F3,sub_grade : F4,sub_grade : F5,sub_grade : G1,sub_grade : G2,sub_grade : G3,sub_grade : G4,sub_grade : G5,home_ownership : ANY,home_ownership : MORTGAGE,home_ownership : OWN,home_ownership : RENT,verification_status : Not Verified,verification_status : Source Verified,verification_status : Verified,loan_status : Charged Off,loan_status : Current,loan_status : Default,loan_status : Fully Paid,loan_status : In Grace Period,loan_status : Issued,loan_status : Late (16-30 days),loan_status : Late (31-120 days),purpose : car,purpose : credit_card,purpose : debt_consolidation,purpose : educational,purpose : home_improvement,purpose : house,purpose : major_purchase,purpose : medical,purpose : moving,purpose : other,purpose : renewable_energy,purpose : small_business,purpose : vacation,purpose : wedding,addr_state : AK,addr_state : AL,addr_state : AR,addr_state : AZ,addr_state : CA,addr_state : CO,addr_state : CT,addr_state : DC,addr_state : DE,addr_state : FL,addr_state : GA,addr_state : HI,addr_state : IL,addr_state : IN,addr_state : KS,addr_state : KY,addr_state : LA,addr_state : MA,addr_state : MD,addr_state : ME,addr_state : MI,addr_state : MN,addr_state : MO,addr_state : MS,addr_state : MT,addr_state : NC,addr_state : ND,addr_state : NE,addr_state : NH,addr_state : NJ,addr_state : NM,addr_state : NV,addr_state : NY,addr_state : OH,addr_state : OK,addr_state : OR,addr_state : PA,addr_state : RI,addr_state : SC,addr_state : SD,addr_state : TN,addr_state : TX,addr_state : UT,addr_state : VA,addr_state : VT,addr_state : WA,addr_state : WI,addr_state : WV,addr_state : WY,initial_list_status : f,initial_list_status : w
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,False,False,False,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421089,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
421090,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
421091,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
421092,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
421093,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,True,True,True,False,False,False,True,True,True,True,True,True,True,True,True,True,True,False,True,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [57]:
#sum the boolean values to get the sum of missing values by variable
pd.options.display.max_rows = None
loan_data.isnull().sum()

id                                            0
member_id                                     0
loan_amnt                                     0
funded_amnt                                   0
funded_amnt_inv                               0
term                                          0
int_rate                                      0
installment                                   0
grade                                         0
sub_grade                                     0
emp_title                                 23874
emp_length                                23817
home_ownership                                0
annual_inc                                    0
verification_status                           0
issue_d                                       0
loan_status                                   0
pymnt_plan                                    0
url                                           0
desc                                     421049
purpose                                       0
title                                       132
zip_code                                      0
addr_state                                    0
dti                                           0
delinq_2yrs                                   0
earliest_cr_line                              0
inq_last_6mths                                0
mths_since_last_delinq                   203961
mths_since_last_record                   346679
open_acc                                      0
pub_rec                                       0
revol_bal                                     0
revol_util                                  162
total_acc                                     0
initial_list_status                           0
out_prncp                                     0
out_prncp_inv                                 0
total_pymnt                                   0
total_pymnt_inv                               0
total_rec_prncp                               0
total_rec_int                                 0
total_rec_late_fee                            0
recoveries                                    0
collection_recovery_fee                       0
last_pymnt_d                              17283
last_pymnt_amnt                               0
next_pymnt_d                              25757
last_credit_pull_d                           11
collections_12_mths_ex_med                    0
mths_since_last_major_derog              298365
policy_code                                   0
application_type                              0
annual_inc_joint                         420583
dti_joint                                420585
verification_status_joint                420583
acc_now_delinq                                0
tot_coll_amt                                  0
tot_cur_bal                                   0
open_acc_6m                              399722
open_il_6m                               399722
open_il_12m                              399722
open_il_24m                              399722
mths_since_rcnt_il                       400284
total_bal_il                             399722
il_util                                  402477
open_rv_12m                              399722
open_rv_24m                              399722
max_bal_bc                               399722
all_util                                 399722
total_rev_hi_lim                              0
inq_fi                                   399722
total_cu_tl                              399722
inq_last_12m                             399722
emp_length_int                            23817
term_int                                      0
earliest_cr_line_date                         0
days_since_earliest_cr_line                   0
mths_since_earliest_cr_line                   0
issue_d_date                                  0
days_since_issue_d                            0
mths_since_issue_d                            0
grade : A                                     0
grade : B                                     0
grade : C                                     0
grade : D                                     0
grade : E                                     0
grade : F                                     0
grade : G                                     0
sub_grade : A1                                0
sub_grade : A2                                0
sub_grade : A3                                0
sub_grade : A4                                0
sub_grade : A5                                0
sub_grade : B1                                0
sub_grade : B2                                0
sub_grade : B3                                0
sub_grade : B4                                0
sub_grade : B5                                0
sub_grade : C1                                0
sub_grade : C2                                0
sub_grade : C3                                0
sub_grade : C4                                0
sub_grade : C5                                0
sub_grade : D1                                0
sub_grade : D2                                0
sub_grade : D3                                0
sub_grade : D4                                0
sub_grade : D5                                0
sub_grade : E1                                0
sub_grade : E2                                0
sub_grade : E3                                0
sub_grade : E4                                0
sub_grade : E5                                0
sub_grade : F1                                0
sub_grade : F2                                0
sub_grade : F3                                0
sub_grade : F4                                0
sub_grade : F5                                0
sub_grade : G1                                0
sub_grade : G2                                0
sub_grade : G3                                0
sub_grade : G4                                0
sub_grade : G5                                0
home_ownership : ANY                          0
home_ownership : MORTGAGE                     0
home_ownership : OWN                          0
home_ownership : RENT                         0
verification_status : Not Verified            0
verification_status : Source Verified         0
verification_status : Verified                0
loan_status : Charged Off                     0
loan_status : Current                         0
loan_status : Default                         0
loan_status : Fully Paid                      0
loan_status : In Grace Period                 0
loan_status : Issued                          0
loan_status : Late (16-30 days)               0
loan_status : Late (31-120 days)              0
purpose : car                                 0
purpose : credit_card                         0
purpose : debt_consolidation                  0
purpose : educational                         0
purpose : home_improvement                    0
purpose : house                               0
purpose : major_purchase                      0
purpose : medical                             0
purpose : moving                              0
purpose : other                               0
purpose : renewable_energy                    0
purpose : small_business                      0
purpose : vacation                            0
purpose : wedding                             0
addr_state : AK                               0
addr_state : AL                               0
addr_state : AR                               0
addr_state : AZ                               0
addr_state : CA                               0
addr_state : CO                               0
addr_state : CT                               0
addr_state : DC                               0
addr_state : DE                               0
addr_state : FL                               0
addr_state : GA                               0
addr_state : HI                               0
addr_state : IL                               0
addr_state : IN                               0
addr_state : KS                               0
addr_state : KY                               0
addr_state : LA                               0
addr_state : MA                               0
addr_state : MD                               0
addr_state : ME                               0
addr_state : MI                               0
addr_state : MN                               0
addr_state : MO                               0
addr_state : MS                               0
addr_state : MT                               0
addr_state : NC                               0
addr_state : ND                               0
addr_state : NE                               0
addr_state : NH                               0
addr_state : NJ                               0
addr_state : NM                               0
addr_state : NV                               0
addr_state : NY                               0
addr_state : OH                               0
addr_state : OK                               0
addr_state : OR                               0
addr_state : PA                               0
addr_state : RI                               0
addr_state : SC                               0
addr_state : SD                               0
addr_state : TN                               0
addr_state : TX                               0
addr_state : UT                               0
addr_state : VA                               0
addr_state : VT                               0
addr_state : WA                               0
addr_state : WI                               0
addr_state : WV                               0
addr_state : WY                               0
initial_list_status : f                       0
initial_list_status : w                       0
dtype: int64

In [58]:
#Imputing missing variables
pd.options.display.max_rows = 100

In [59]:
# loan_data['total_rev_hi_lim'].fillna(loan_data ['funded_amnt'], inplace = True )
loan_data['total_rev_hi_lim'] = loan_data['total_rev_hi_lim'].fillna(loan_data ['funded_amnt'])

In [60]:
loan_data['total_rev_hi_lim'].isnull().sum()

np.int64(0)

In [61]:
# loan_data['annual_inc'].fillna(loan_data ['funded_amnt'], inplace = True)

In [62]:
# We fill the missing values with the mean value of the non-missing values.
loan_data['annual_inc'] = loan_data['annual_inc'].fillna(loan_data['annual_inc'].mean())

In [63]:
# We fill the missing values with zeroes.
loan_data['mths_since_earliest_cr_line'] = loan_data['mths_since_earliest_cr_line'].fillna(0)

In [64]:
# List of columns that need to be filled with 0
cols_to_fix = [
    'emp_length_int', 'delinq_2yrs', 'inq_last_6mths', 
    'open_acc', 'pub_rec', 'total_acc', 
    'mths_since_earliest_cr_line', 'acc_now_delinq'
]

# Update the dataframe in one clean step
loan_data[cols_to_fix] = loan_data[cols_to_fix].fillna(0)

##### Cleaned data

In [65]:
# loan_data.to_parquet('loan_data_cleaned.parquet', index=False)
loan_data.to_parquet('loan_data_monitoring.parquet', engine='pyarrow', index=False)

In [66]:
# Load the file
loan_data = pd.read_parquet('loan_data_monitoring.parquet')

# View the first 5 rows
loan_data['term_int'].head()

0    60
1    36
2    36
3    60
4    60
Name: term_int, dtype: int64