### Import Libraries

In [1]:
import pandas as pd
import numpy as np

### Loading data and selecting features

#### Import data

In [2]:
#preserve indexes for correct matching
loan_data_inputs_train = pd.read_csv('loan_data_inputs_train.csv', index_col = 0) #use content of the first column as indexes
# loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0, header = None) #don't import header for the df with targets
loan_data_target_train = pd.read_csv('loan_data_targets_train.csv', index_col = 0)
loan_data_inputs_test = pd.read_csv('loan_data_inputs_test.csv', index_col = 0)
loan_data_target_test = pd.read_csv('loan_data_targets_test.csv', index_col = 0)

#### Explore data

In [3]:
loan_data_inputs_train.head()

,Unnamed: 0,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,...,dti:21.7-22.4,dti:22.4-35,dti:>35,mths_since_last_record:Missing,mths_since_last_record:0-2,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
456615,456615,10588532,12470492,15000,15000,15000.0,36 months,8.90,476.30,A,...,0,0,0,1,0,0,0,0,0,0
451541,451541,11215587,13127755,8000,8000,8000.0,60 months,18.25,204.24,D,...,0,1,0,1,0,0,0,0,0,0
394474,394474,14218271,16270650,12150,12150,12100.0,60 months,18.92,314.65,D,...,0,1,0,1,0,0,0,0,0,0
110294,110294,6504869,8057011,10000,10000,10000.0,36 months,6.03,304.36,A,...,0,0,0,1,0,0,0,0,0,0
139343,139343,3929378,5022980,15825,15825,15825.0,36 months,12.12,526.53,B,...,0,0,0,1,0,0,0,0,0,0

In [4]:
loan_data_target_train.head()

        good_bad
456615         1
451541         1
394474         1
110294         1
139343         0

In [5]:
loan_data_inputs_train.shape

(373028, 326)

In [6]:
loan_data_target_train.shape

(373028, 1)

In [7]:
loan_data_inputs_test.shape

(93257, 326)

In [8]:
loan_data_target_test.shape

(93257, 1)

#### Building the PD model
#### Selecting features

In [9]:
# USe dummy variables only excluding the reference variables
loan_data_inputs_train.columns = loan_data_inputs_train.columns.str.replace(' : ', ':')
loan_data_inputs_train.columns = loan_data_inputs_train.columns.str.strip()

inputs_train_with_ref_cat = loan_data_inputs_train.loc[:, [

# Grade
'grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',

# Home ownership
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',

# Address state
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',

# Verification status
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',

# Purpose
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',

# Initial list status
'initial_list_status:f',
'initial_list_status:w',

# Term
'term:36',
'term:60',

# Employment length
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',

# Months since issue
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',

# Interest rate
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',

# Months since earliest credit line
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',

# Delinquencies
'delinq_2yrs:0',
'delinq_2yrs:1-3',
'delinq_2yrs:>=4',

# Inquiries
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',

# Open accounts
'open_acc:0',
'open_acc:1-3',
'open_acc:4-12',
'open_acc:13-17',
'open_acc:18-22',
'open_acc:23-25',
'open_acc:26-30',
'open_acc:>=31',

# Public records
'pub_rec:0-2',
'pub_rec:3-4',
'pub_rec:>=5',

# Total accounts
'total_acc:<=27',
'total_acc:28-51',
'total_acc:>=52',

# Accounts delinquent
'acc_now_delinq:0',
'acc_now_delinq:>=1',

# Revolving credit limit
'total_rev_hi_lim:<=5K',
'total_rev_hi_lim:5K-10K',
'total_rev_hi_lim:10K-20K',
'total_rev_hi_lim:20K-30K',
'total_rev_hi_lim:30K-40K',
'total_rev_hi_lim:40K-55K',
'total_rev_hi_lim:55K-95K',
'total_rev_hi_lim:>95K',

# Annual income
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',

# Debt to income
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',

# Months since last delinquency
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',

# Months since last record
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86'

]]

In [10]:
# store the names of the reference category dummy variables in a list.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'delinq_2yrs:>=4',
'inq_last_6mths:>6',
'open_acc:0',
'pub_rec:0-2',
'total_acc:<=27',
'acc_now_delinq:0',
'total_rev_hi_lim:<=5K',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

##### Remove reference categories

In [11]:
# From the dataframe with input variables, we drop the variables with variable names in the list with reference categories. 
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
456615,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
451541,0,0,0,1,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,0
394474,0,0,0,1,0,0,1,0,0,0,...,0,1,0,0,1,0,0,0,0,0
110294,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
139343,0,1,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

### Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn import metrics

In [13]:
#create instance of logistic reg class i.e model object
reg = LogisticRegression()
# reg = LogisticRegression(max_iter=1000)

In [14]:
#make sure all rows are printed
pd.options.display.max_rows = None

In [15]:
#estimate the model by fitting(training) the inputs and the targets and store result in reg object
# inputs_train - all the independent dummy variables without the reference categories
# loan_data_targets_train - dependent variable i.e good bad indicator
reg.fit(inputs_train, loan_data_target_train) #model learns relationship between X and y

D:\credit_risk_modelling_python\venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [16]:
#get coefficients of the pd model 
# base risk when all variables are zero.
# It is the starting probability.

reg.intercept_ #gives intercept

array([-0.32172136])

In [17]:
#gives the coefficients in the order of the dependant var from inputs df 
#How much that variable increases or decreases the probability of default.

reg.coef_

array([[ 9.11648957e-01,  7.17320474e-01,  5.36324730e-01,
         3.61235953e-01,  2.09927099e-01,  5.93674585e-02,
         7.18718804e-02,  1.19428621e-01,  7.88126698e-02,
         9.53033338e-02,  8.89069503e-02,  1.01712023e-01,
         1.09777547e-01,  1.64644863e-01,  1.09209145e-01,
         2.26197023e-01,  2.98529802e-01,  2.48365580e-01,
         3.02079055e-01,  3.56214167e-01,  5.02224953e-01,
         1.07333307e-01,  5.16226750e-04,  2.73433519e-01,
         1.59422934e-01,  1.55845592e-01,  2.38237812e-01,
         5.57529202e-02,  8.01811507e-02,  1.18443296e-01,
         1.25866283e-01,  9.15247698e-02,  5.94206405e-02,
         1.27808646e-01,  1.11336671e+00,  9.20819540e-01,
         8.21879129e-01,  6.10539158e-01,  4.77892908e-01,
         2.31532857e-01, -2.52927623e-02,  9.92927829e-01,
         6.33611908e-01,  3.61719826e-01,  1.41715800e-01,
         8.17373526e-02,  4.63251084e-02,  8.94172598e-02,
         1.38403959e-01,  1.34288755e-01, -1.20445050e-01,
        -1.47981971e-01,  3.30448313e-01,  1.79720365e-01,
        -2.37224681e-02,  1.68109231e-02, -2.70045811e-02,
        -5.31250829e-02, -6.46228634e-02, -4.20808486e-02,
        -5.08751973e-02, -4.40256242e-02,  1.06087170e-02,
         7.40898724e-02, -1.32207876e-02,  1.59418254e-02,
         1.81919694e-01,  3.46178059e-02,  9.67948173e-03,
         1.90712572e-02,  6.33346158e-03,  7.56645352e-02,
         5.88634580e-02,  2.27299700e-01, -1.88053793e-01,
        -1.24936365e-01, -1.86030875e-02,  2.56592476e-02,
         1.18041826e-01,  1.75290896e-01,  2.52508390e-01,
         2.74612274e-01,  3.30809249e-01,  4.03158460e-01,
         3.64674613e-01,  9.72752196e-02,  1.62586537e-01,
         1.67341081e-01,  1.27967712e-01,  4.94417285e-02,
        -3.82759919e-02, -4.68359019e-02, -1.09170659e-01,
        -1.43361518e-01,  6.04730554e-02,  9.00026350e-02,
         1.28026375e-01,  9.28843554e-02,  1.15126302e-01,
         1.24963250e-01,  2.19095330e-01,  3.39061866e-01,
        -1.62872906e-02,  4.41917483e-02]])

In [18]:
# These coefficients tell us: How each variable affects default risk, Direction of impact, Strength of impact
# Positive coefficient: → Increases probability of being good (non-default)
# Negative coefficient: → Increases probability of default

In [19]:
# Connect coefficients to var names
feature_name = inputs_train.columns.values

In [20]:
#summary table df with feature names and corresponding coefficients
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
# Creates a dataframe with a column titled 'Feature name' and row values contained in the 'feature_name' variable.
summary_table['Coefficients'] = np.transpose(reg.coef_) #Transpose converts row → column.
# Creates a new column in the dataframe, called 'Coefficients', with row values the transposed coefficients from the 'LogisticRegression' object.
summary_table.index = summary_table.index + 1
# Increases the index of every row of the dataframe with 1.
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
# Assigns values of the row with index 0 of the dataframe.
summary_table = summary_table.sort_index()
# Sorts the dataframe by index.
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.321721
1                                grade:A      0.911649
2                                grade:B      0.717320
3                                grade:C      0.536325
4                                grade:D      0.361236
5                                grade:E      0.209927
6                                grade:F      0.059367
7                     home_ownership:OWN      0.071872
8                home_ownership:MORTGAGE      0.119429
9                       addr_state:NM_VA      0.078813
10                         addr_state:NY      0.095303
11          addr_state:OK_TN_MO_LA_MD_NC      0.088907
12                         addr_state:CA      0.101712
13                addr_state:UT_KY_AZ_NJ      0.109778
14             addr_state:AR_MI_PA_OH_MN      0.164645
15             addr_state:RI_MA_DE_SD_IN      0.109209
16                   addr_state:GA_WA_OR      0.226197
17                      addr_state:WI_MT      0.298530
18                         addr_state:TX      0.248366
19                      addr_state:IL_CT      0.302079
20          addr_state:KS_SC_CO_VT_AK_MS      0.356214
21          addr_state:WV_NH_WY_DC_ME_ID      0.502225
22      verification_status:Not Verified      0.107333
23   verification_status:Source Verified      0.000516
24                   purpose:credit_card      0.273434
25            purpose:debt_consolidation      0.159423
26            purpose:oth__med__vacation      0.155846
27   purpose:major_purch__car__home_impr      0.238238
28                 initial_list_status:w      0.055753
29                               term:36      0.080181
30                          emp_length:1      0.118443
31                        emp_length:2-4      0.125866
32                        emp_length:5-6      0.091525
33                        emp_length:7-9      0.059421
34                         emp_length:10      0.127809
35                mths_since_issue_d:<38      1.113367
36              mths_since_issue_d:38-39      0.920820
37              mths_since_issue_d:40-41      0.821879
38              mths_since_issue_d:42-48      0.610539
39              mths_since_issue_d:49-52      0.477893
40              mths_since_issue_d:53-64      0.231533
41              mths_since_issue_d:65-84     -0.025293
42                       int_rate:<9.548      0.992928
43                 int_rate:9.548-12.025      0.633612
44                 int_rate:12.025-15.74      0.361720
45                 int_rate:15.74-20.281      0.141716
46   mths_since_earliest_cr_line:141-164      0.081737
47   mths_since_earliest_cr_line:165-247      0.046325
48   mths_since_earliest_cr_line:248-270      0.089417
49   mths_since_earliest_cr_line:271-352      0.138404
50      mths_since_earliest_cr_line:>352      0.134289
51                         delinq_2yrs:0     -0.120445
52                       delinq_2yrs:1-3     -0.147982
53                      inq_last_6mths:0      0.330448
54                    inq_last_6mths:1-2      0.179720
55                    inq_last_6mths:3-6     -0.023722
56                          open_acc:1-3      0.016811
57                         open_acc:4-12     -0.027005
58                        open_acc:13-17     -0.053125
59                        open_acc:18-22     -0.064623
60                        open_acc:23-25     -0.042081
61                        open_acc:26-30     -0.050875
62                         open_acc:>=31     -0.044026
63                           pub_rec:3-4      0.010609
64                           pub_rec:>=5      0.074090
65                       total_acc:28-51     -0.013221
66                        total_acc:>=52      0.015942
67                    acc_now_delinq:>=1      0.181920
68               total_rev_hi_lim:5K-10K      0.034618
69              total_rev_hi_lim:10K-20K      0.009679
70              total_rev_hi_lim:20K-30K      0.019071
71              total_rev_hi_lim:30K-40K      0.006333
72              total_rev_hi_lim:40K-55K      0.075665
73              total_rev_hi_lim:55K-95K      0.058863
74                 total_rev_hi_lim:>95K      0.227300
75                    annual_inc:20K-30K     -0.188054
76                    annual_inc:30K-40K     -0.124936
77                    annual_inc:40K-50K     -0.018603
78                    annual_inc:50K-60K      0.025659
79                    annual_inc:60K-70K      0.118042
80                    annual_inc:70K-80K      0.175291
81                    annual_inc:80K-90K      0.252508
82                   annual_inc:90K-100K      0.274612
83                  annual_inc:100K-120K      0.330809
84                  annual_inc:120K-140K      0.403158
85                      annual_inc:>140K      0.364675
86                             dti:<=1.4      0.097275
87                           dti:1.4-3.5      0.162587
88                           dti:3.5-7.7      0.167341
89                          dti:7.7-10.5      0.127968
90                         dti:10.5-16.1      0.049442
91                         dti:16.1-20.3     -0.038276
92                         dti:20.3-21.7     -0.046836
93                         dti:21.7-22.4     -0.109171
94                           dti:22.4-35     -0.143362
95        mths_since_last_delinq:Missing      0.060473
96           mths_since_last_delinq:4-30      0.090003
97          mths_since_last_delinq:31-56      0.128026
98           mths_since_last_delinq:>=57      0.092884
99        mths_since_last_record:Missing      0.115126
100          mths_since_last_record:3-20      0.124963
101         mths_since_last_record:21-31      0.219095
102         mths_since_last_record:32-80      0.339062
103         mths_since_last_record:81-86     -0.016287
104           mths_since_last_record:>86      0.044192

### Bulding a logistic regression model with P-values

Check statistical significance of a dummy variable

A p-value answers:
If this variable had NO real effect, what is the probability we would see this result by chance?
Small p-value → likely real effect
Large p-value → likely random noise
p < 0.05 → coefficient of var is statistically significant
p > 0.05 → coefficient not statistically significant

To be able to calculate the multivariate p values - alter the fit method from the logistic reg

In [21]:
# assess which var contribute to predicting borrower default and which one don't (statistical significance)
#It gives us proper multivariate p-values.

# P values for sklearn logistic regression.

# Class to display p-values for logistic regression in sklearn.

from sklearn import linear_model
import scipy.stats as stat

class LogisticRegression_with_p_values:
    
    def __init__(self,*args,**kwargs):#,**kwargs):
        self.model = linear_model.LogisticRegression(*args,**kwargs)#,**args)

    def fit(self,X,y):
        self.model.fit(X,y)
        
        #### Get p-values for the fitted model ####
        denom = (2.0 * (1.0 + np.cosh(self.model.decision_function(X))))
        denom = np.tile(denom,(X.shape[1],1)).T
        F_ij = np.dot((X / denom).T,X) ## Fisher Information Matrix
        Cramer_Rao = np.linalg.inv(F_ij) ## Inverse Information Matrix
        sigma_estimates = np.sqrt(np.diagonal(Cramer_Rao))
        z_scores = self.model.coef_[0] / sigma_estimates # z-score for eaach model coefficient
        p_values = [stat.norm.sf(abs(x)) * 2 for x in z_scores] ### two tailed test for p-values
        
        self.coef_ = self.model.coef_
        self.intercept_ = self.model.intercept_
        self.p_values = p_values

In [22]:
reg = LogisticRegression_with_p_values()
# We create an instance of an object from the newly created 'LogisticRegression_with_p_values()' class.

In [23]:
reg.fit(inputs_train, loan_data_target_train)
# Estimates the coefficients of the object from the 'LogisticRegression' class
# with inputs (independent variables) contained in the first dataframe
# and targets (dependent variables) contained in the second dataframe.

D:\credit_risk_modelling_python\venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [24]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                            Feature name  Coefficients
0                              Intercept     -0.321721
1                                grade:A      0.911649
2                                grade:B      0.717320
3                                grade:C      0.536325
4                                grade:D      0.361236
5                                grade:E      0.209927
6                                grade:F      0.059367
7                     home_ownership:OWN      0.071872
8                home_ownership:MORTGAGE      0.119429
9                       addr_state:NM_VA      0.078813
10                         addr_state:NY      0.095303
11          addr_state:OK_TN_MO_LA_MD_NC      0.088907
12                         addr_state:CA      0.101712
13                addr_state:UT_KY_AZ_NJ      0.109778
14             addr_state:AR_MI_PA_OH_MN      0.164645
15             addr_state:RI_MA_DE_SD_IN      0.109209
16                   addr_state:GA_WA_OR      0.226197
17                      addr_state:WI_MT      0.298530
18                         addr_state:TX      0.248366
19                      addr_state:IL_CT      0.302079
20          addr_state:KS_SC_CO_VT_AK_MS      0.356214
21          addr_state:WV_NH_WY_DC_ME_ID      0.502225
22      verification_status:Not Verified      0.107333
23   verification_status:Source Verified      0.000516
24                   purpose:credit_card      0.273434
25            purpose:debt_consolidation      0.159423
26            purpose:oth__med__vacation      0.155846
27   purpose:major_purch__car__home_impr      0.238238
28                 initial_list_status:w      0.055753
29                               term:36      0.080181
30                          emp_length:1      0.118443
31                        emp_length:2-4      0.125866
32                        emp_length:5-6      0.091525
33                        emp_length:7-9      0.059421
34                         emp_length:10      0.127809
35                mths_since_issue_d:<38      1.113367
36              mths_since_issue_d:38-39      0.920820
37              mths_since_issue_d:40-41      0.821879
38              mths_since_issue_d:42-48      0.610539
39              mths_since_issue_d:49-52      0.477893
40              mths_since_issue_d:53-64      0.231533
41              mths_since_issue_d:65-84     -0.025293
42                       int_rate:<9.548      0.992928
43                 int_rate:9.548-12.025      0.633612
44                 int_rate:12.025-15.74      0.361720
45                 int_rate:15.74-20.281      0.141716
46   mths_since_earliest_cr_line:141-164      0.081737
47   mths_since_earliest_cr_line:165-247      0.046325
48   mths_since_earliest_cr_line:248-270      0.089417
49   mths_since_earliest_cr_line:271-352      0.138404
50      mths_since_earliest_cr_line:>352      0.134289
51                         delinq_2yrs:0     -0.120445
52                       delinq_2yrs:1-3     -0.147982
53                      inq_last_6mths:0      0.330448
54                    inq_last_6mths:1-2      0.179720
55                    inq_last_6mths:3-6     -0.023722
56                          open_acc:1-3      0.016811
57                         open_acc:4-12     -0.027005
58                        open_acc:13-17     -0.053125
59                        open_acc:18-22     -0.064623
60                        open_acc:23-25     -0.042081
61                        open_acc:26-30     -0.050875
62                         open_acc:>=31     -0.044026
63                           pub_rec:3-4      0.010609
64                           pub_rec:>=5      0.074090
65                       total_acc:28-51     -0.013221
66                        total_acc:>=52      0.015942
67                    acc_now_delinq:>=1      0.181920
68               total_rev_hi_lim:5K-10K      0.034618
69              total_rev_hi_lim:10K-20K      0.009679
70              total_rev_hi_lim:20K-30K      0.019071
71              total_rev_hi_lim:30K-40K      0.006333
72              total_rev_hi_lim:40K-55K      0.075665
73              total_rev_hi_lim:55K-95K      0.058863
74                 total_rev_hi_lim:>95K      0.227300
75                    annual_inc:20K-30K     -0.188054
76                    annual_inc:30K-40K     -0.124936
77                    annual_inc:40K-50K     -0.018603
78                    annual_inc:50K-60K      0.025659
79                    annual_inc:60K-70K      0.118042
80                    annual_inc:70K-80K      0.175291
81                    annual_inc:80K-90K      0.252508
82                   annual_inc:90K-100K      0.274612
83                  annual_inc:100K-120K      0.330809
84                  annual_inc:120K-140K      0.403158
85                      annual_inc:>140K      0.364675
86                             dti:<=1.4      0.097275
87                           dti:1.4-3.5      0.162587
88                           dti:3.5-7.7      0.167341
89                          dti:7.7-10.5      0.127968
90                         dti:10.5-16.1      0.049442
91                         dti:16.1-20.3     -0.038276
92                         dti:20.3-21.7     -0.046836
93                         dti:21.7-22.4     -0.109171
94                           dti:22.4-35     -0.143362
95        mths_since_last_delinq:Missing      0.060473
96           mths_since_last_delinq:4-30      0.090003
97          mths_since_last_delinq:31-56      0.128026
98           mths_since_last_delinq:>=57      0.092884
99        mths_since_last_record:Missing      0.115126
100          mths_since_last_record:3-20      0.124963
101         mths_since_last_record:21-31      0.219095
102         mths_since_last_record:32-80      0.339062
103         mths_since_last_record:81-86     -0.016287
104           mths_since_last_record:>86      0.044192

In [25]:
# This is a list.
p_values = reg.p_values
# We take the result of the newly added method 'p_values' and store it in a variable 'p_values'.

In [26]:
# Add the intercept for completeness.
p_values = np.append(np.nan, np.array(p_values))
# We add the value 'NaN' in the beginning of the variable with p-values.

In [27]:
summary_table['p_values'] = p_values
# In the 'summary_table' dataframe, we add a new column, called 'p_values', containing the values from the 'p_values' variable.

In [28]:
summary_table

                            Feature name  Coefficients       p_values
0                              Intercept     -0.321721            NaN
1                                grade:A      0.911649   6.151087e-23
2                                grade:B      0.717320   6.747789e-31
3                                grade:C      0.536325   1.452602e-20
4                                grade:D      0.361236   4.706239e-11
5                                grade:E      0.209927   2.038303e-05
6                                grade:F      0.059367   2.470670e-01
7                     home_ownership:OWN      0.071872   3.409690e-04
8                home_ownership:MORTGAGE      0.119429   5.592318e-21
9                       addr_state:NM_VA      0.078813   1.396556e-02
10                         addr_state:NY      0.095303   8.398519e-05
11          addr_state:OK_TN_MO_LA_MD_NC      0.088907   1.210383e-04
12                         addr_state:CA      0.101712   1.554354e-06
13                addr_state:UT_KY_AZ_NJ      0.109778   9.957193e-06
14             addr_state:AR_MI_PA_OH_MN      0.164645   2.189589e-13
15             addr_state:RI_MA_DE_SD_IN      0.109209   2.362364e-04
16                   addr_state:GA_WA_OR      0.226197   2.169672e-17
17                      addr_state:WI_MT      0.298530   5.234711e-10
18                         addr_state:TX      0.248366   9.200871e-22
19                      addr_state:IL_CT      0.302079   4.463088e-25
20          addr_state:KS_SC_CO_VT_AK_MS      0.356214   1.010766e-30
21          addr_state:WV_NH_WY_DC_ME_ID      0.502225   8.199216e-22
22      verification_status:Not Verified      0.107333   3.048054e-13
23   verification_status:Source Verified      0.000516   9.693793e-01
24                   purpose:credit_card      0.273434   1.331893e-21
25            purpose:debt_consolidation      0.159423   1.432476e-09
26            purpose:oth__med__vacation      0.155846   6.269626e-07
27   purpose:major_purch__car__home_impr      0.238238   4.507871e-14
28                 initial_list_status:w      0.055753   1.989784e-05
29                               term:36      0.080181   1.550415e-08
30                          emp_length:1      0.118443   5.596983e-06
31                        emp_length:2-4      0.125866   2.753294e-11
32                        emp_length:5-6      0.091525   1.894428e-05
33                        emp_length:7-9      0.059421   4.311323e-03
34                         emp_length:10      0.127809   4.260442e-12
35                mths_since_issue_d:<38      1.113367  3.055871e-185
36              mths_since_issue_d:38-39      0.920820  2.985061e-157
37              mths_since_issue_d:40-41      0.821879  1.558411e-131
38              mths_since_issue_d:42-48      0.610539   2.550858e-93
39              mths_since_issue_d:49-52      0.477893   5.012416e-51
40              mths_since_issue_d:53-64      0.231533   9.883877e-15
41              mths_since_issue_d:65-84     -0.025293   3.851039e-01
42                       int_rate:<9.548      0.992928   1.362481e-37
43                 int_rate:9.548-12.025      0.633612   4.683350e-45
44                 int_rate:12.025-15.74      0.361720   1.316434e-22
45                 int_rate:15.74-20.281      0.141716   1.161926e-06
46   mths_since_earliest_cr_line:141-164      0.081737   1.216934e-03
47   mths_since_earliest_cr_line:165-247      0.046325   2.468983e-02
48   mths_since_earliest_cr_line:248-270      0.089417   8.600182e-04
49   mths_since_earliest_cr_line:271-352      0.138404   1.066001e-08
50      mths_since_earliest_cr_line:>352      0.134289   7.734600e-07
51                         delinq_2yrs:0     -0.120445   4.390725e-02
52                       delinq_2yrs:1-3     -0.147982   8.923928e-03
53                      inq_last_6mths:0      0.330448   7.315226e-03
54                    inq_last_6mths:1-2      0.179720   1.441804e-01
55                    inq_last_6mths:3-6     -0.023722   8.477052e-01
56                          open_acc:1-3      0.016811   9.231627e-01
57                         open_acc:4-12     -0.027005   8.744626e-01
58                        open_acc:13-17     -0.053125   7.563838e-01
59                        open_acc:18-22     -0.064623   7.073976e-01
60                        open_acc:23-25     -0.042081   8.118704e-01
61                        open_acc:26-30     -0.050875   7.793096e-01
62                         open_acc:>=31     -0.044026   8.221199e-01
63                           pub_rec:3-4      0.010609   9.069199e-01
64                           pub_rec:>=5      0.074090   6.818536e-01
65                       total_acc:28-51     -0.013221   3.523436e-01
66                        total_acc:>=52      0.015942   6.885011e-01
67                    acc_now_delinq:>=1      0.181920   8.904677e-02
68               total_rev_hi_lim:5K-10K      0.034618   1.600110e-01
69              total_rev_hi_lim:10K-20K      0.009679   6.855140e-01
70              total_rev_hi_lim:20K-30K      0.019071   4.682789e-01
71              total_rev_hi_lim:30K-40K      0.006333   8.297598e-01
72              total_rev_hi_lim:40K-55K      0.075665   1.916964e-02
73              total_rev_hi_lim:55K-95K      0.058863   1.017635e-01
74                 total_rev_hi_lim:>95K      0.227300   5.730794e-05
75                    annual_inc:20K-30K     -0.188054   2.093139e-05
76                    annual_inc:30K-40K     -0.124936   3.498365e-03
77                    annual_inc:40K-50K     -0.018603   6.642407e-01
78                    annual_inc:50K-60K      0.025659   5.541242e-01
79                    annual_inc:60K-70K      0.118042   7.833937e-03
80                    annual_inc:70K-80K      0.175291   1.068250e-04
81                    annual_inc:80K-90K      0.252508   7.934135e-08
82                   annual_inc:90K-100K      0.274612   1.555839e-08
83                  annual_inc:100K-120K      0.330809   6.892746e-12
84                  annual_inc:120K-140K      0.403158   9.402616e-14
85                      annual_inc:>140K      0.364675   5.967200e-13
86                             dti:<=1.4      0.097275   2.922323e-01
87                           dti:1.4-3.5      0.162587   3.833331e-02
88                           dti:3.5-7.7      0.167341   1.598183e-02
89                          dti:7.7-10.5      0.127968   6.359247e-02
90                         dti:10.5-16.1      0.049442   4.613123e-01
91                         dti:16.1-20.3     -0.038276   5.683089e-01
92                         dti:20.3-21.7     -0.046836   4.997106e-01
93                         dti:21.7-22.4     -0.109171   1.342697e-01
94                           dti:22.4-35     -0.143362   3.079528e-02
95        mths_since_last_delinq:Missing      0.060473   3.065700e-01
96           mths_since_last_delinq:4-30      0.090003   1.009213e-01
97          mths_since_last_delinq:31-56      0.128026   3.342897e-02
98           mths_since_last_delinq:>=57      0.092884   1.297463e-01
99        mths_since_last_record:Missing      0.115126   2.088282e-01
100          mths_since_last_record:3-20      0.124963   3.258305e-01
101         mths_since_last_record:21-31      0.219095   7.262024e-02
102         mths_since_last_record:32-80      0.339062   3.869283e-04
103         mths_since_last_record:81-86     -0.016287   8.829633e-01
104           mths_since_last_record:>86      0.044192   6.388594e-01

Retain variables whose coefficients are statistically significant i.e p < 0.05

If ALL dummies insignificant → remove entire variable
If one or few dummy significant → keep entire variable

In [29]:
# We are going to remove some features, the coefficients for all or almost all of the dummy variables for which,
# are not tatistically significant.

# We do that by specifying another list of dummy variables as reference categories, and a list of variables to remove.
# Then, we are going to drop the two datasets from the original list of dummy variables.

# Variables
inputs_train_with_ref_cat = loan_data_inputs_train.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [30]:
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [31]:
inputs_train = inputs_train_with_ref_cat.drop(ref_categories, axis = 1)
inputs_train.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
456615,1,0,0,0,0,0,0,1,0,0,...,0,1,0,0,1,0,0,0,0,0
451541,0,0,0,1,0,0,1,0,0,0,...,1,0,0,0,1,0,0,0,0,0
394474,0,0,0,1,0,0,1,0,0,0,...,0,1,0,0,1,0,0,0,0,0
110294,1,0,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0
139343,0,1,0,0,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

In [32]:
# Here we run a new model.
reg2 = LogisticRegression_with_p_values()
reg2.fit(inputs_train, loan_data_target_train)

D:\credit_risk_modelling_python\venv\Lib\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [33]:
feature_name = inputs_train.columns.values

In [34]:
# Same as above.
summary_table = pd.DataFrame(columns = ['Feature name'], data = feature_name)
summary_table['Coefficients'] = np.transpose(reg2.coef_)
summary_table.index = summary_table.index + 1
summary_table.loc[0] = ['Intercept', reg2.intercept_[0]]
summary_table = summary_table.sort_index()
summary_table

                           Feature name  Coefficients
0                             Intercept     -0.791083
1                               grade:A      1.027107
2                               grade:B      0.866439
3                               grade:C      0.692273
4                               grade:D      0.514298
5                               grade:E      0.347651
6                               grade:F      0.188875
7                    home_ownership:OWN      0.072958
8               home_ownership:MORTGAGE      0.117042
9                      addr_state:NM_VA      0.057471
10                        addr_state:NY      0.063133
11         addr_state:OK_TN_MO_LA_MD_NC      0.056933
12                        addr_state:CA      0.070423
13               addr_state:UT_KY_AZ_NJ      0.077512
14            addr_state:AR_MI_PA_OH_MN      0.134562
15            addr_state:RI_MA_DE_SD_IN      0.082679
16                  addr_state:GA_WA_OR      0.193456
17                     addr_state:WI_MT      0.298998
18                        addr_state:TX      0.214345
19                     addr_state:IL_CT      0.268740
20         addr_state:KS_SC_CO_VT_AK_MS      0.295215
21         addr_state:WV_NH_WY_DC_ME_ID      0.483812
22     verification_status:Not Verified      0.099518
23  verification_status:Source Verified     -0.000991
24                  purpose:credit_card      0.299656
25           purpose:debt_consolidation      0.184666
26           purpose:oth__med__vacation      0.183250
27  purpose:major_purch__car__home_impr      0.256971
28                initial_list_status:w      0.057397
29                              term:36      0.077356
30                         emp_length:1      0.117554
31                       emp_length:2-4      0.125062
32                       emp_length:5-6      0.088656
33                       emp_length:7-9      0.056347
34                        emp_length:10      0.127912
35               mths_since_issue_d:<38      1.087614
36             mths_since_issue_d:38-39      0.898317
37             mths_since_issue_d:40-41      0.800145
38             mths_since_issue_d:42-48      0.587456
39             mths_since_issue_d:49-52      0.460871
40             mths_since_issue_d:53-64      0.210367
41             mths_since_issue_d:65-84     -0.050746
42                      int_rate:<9.548      1.032490
43                int_rate:9.548-12.025      0.620333
44                int_rate:12.025-15.74      0.341537
45                int_rate:15.74-20.281      0.125881
46  mths_since_earliest_cr_line:141-164      0.062932
47  mths_since_earliest_cr_line:165-247      0.030811
48  mths_since_earliest_cr_line:248-270      0.069679
49  mths_since_earliest_cr_line:271-352      0.125008
50     mths_since_earliest_cr_line:>352      0.121982
51                     inq_last_6mths:0      0.372079
52                   inq_last_6mths:1-2      0.223549
53                   inq_last_6mths:3-6      0.012637
54                   acc_now_delinq:>=1      0.171933
55                   annual_inc:20K-30K     -0.117156
56                   annual_inc:30K-40K     -0.063623
57                   annual_inc:40K-50K      0.044912
58                   annual_inc:50K-60K      0.090131
59                   annual_inc:60K-70K      0.189258
60                   annual_inc:70K-80K      0.245552
61                   annual_inc:80K-90K      0.325316
62                  annual_inc:90K-100K      0.347899
63                 annual_inc:100K-120K      0.406567
64                 annual_inc:120K-140K      0.487459
65                     annual_inc:>140K      0.428926
66                            dti:<=1.4      0.108443
67                          dti:1.4-3.5      0.235175
68                          dti:3.5-7.7      0.187648
69                         dti:7.7-10.5      0.146449
70                        dti:10.5-16.1      0.060175
71                        dti:16.1-20.3     -0.028908
72                        dti:20.3-21.7     -0.037869
73                        dti:21.7-22.4     -0.102563
74                          dti:22.4-35     -0.132105
75       mths_since_last_delinq:Missing      0.132340
76          mths_since_last_delinq:4-30      0.146303
77         mths_since_last_delinq:31-56      0.197426
78          mths_since_last_delinq:>=57      0.161338
79       mths_since_last_record:Missing      0.169906
80          mths_since_last_record:3-20      0.134628
81         mths_since_last_record:21-31      0.208203
82         mths_since_last_record:32-80      0.399625
83         mths_since_last_record:81-86      0.013924
84           mths_since_last_record:>86      0.092544

In [35]:
# We add the 'p_values' here, just as we did before.
p_values = reg2.p_values
p_values = np.append(np.nan,np.array(p_values))
summary_table['p_values'] = p_values
summary_table
# Here we get the results for our final PD model.

                           Feature name  Coefficients       p_values
0                             Intercept     -0.791083            NaN
1                               grade:A      1.027107   1.162773e-28
2                               grade:B      0.866439   5.723867e-46
3                               grade:C      0.692273   1.110159e-34
4                               grade:D      0.514298   5.620296e-22
5                               grade:E      0.347651   1.830033e-13
6                               grade:F      0.188875   1.191602e-04
7                    home_ownership:OWN      0.072958   2.666980e-04
8               home_ownership:MORTGAGE      0.117042   2.291496e-20
9                      addr_state:NM_VA      0.057471   7.392551e-02
10                        addr_state:NY      0.063133   9.240132e-03
11         addr_state:OK_TN_MO_LA_MD_NC      0.056933   1.394990e-02
12                        addr_state:CA      0.070423   9.118039e-04
13               addr_state:UT_KY_AZ_NJ      0.077512   1.831467e-03
14            addr_state:AR_MI_PA_OH_MN      0.134562   2.157534e-09
15            addr_state:RI_MA_DE_SD_IN      0.082679   5.444671e-03
16                  addr_state:GA_WA_OR      0.193456   4.044426e-13
17                     addr_state:WI_MT      0.298998   7.085121e-10
18                        addr_state:TX      0.214345   1.423154e-16
19                     addr_state:IL_CT      0.268740   3.454747e-20
20         addr_state:KS_SC_CO_VT_AK_MS      0.295215   6.224937e-22
21         addr_state:WV_NH_WY_DC_ME_ID      0.483812   3.150516e-20
22     verification_status:Not Verified      0.099518   9.736856e-12
23  verification_status:Source Verified     -0.000991   9.410405e-01
24                  purpose:credit_card      0.299656   3.603383e-26
25           purpose:debt_consolidation      0.184666   1.260111e-12
26           purpose:oth__med__vacation      0.183250   3.413307e-09
27  purpose:major_purch__car__home_impr      0.256971   2.101170e-16
28                initial_list_status:w      0.057397   1.107048e-05
29                              term:36      0.077356   3.154088e-08
30                         emp_length:1      0.117554   6.417246e-06
31                       emp_length:2-4      0.125062   3.499708e-11
32                       emp_length:5-6      0.088656   3.377576e-05
33                       emp_length:7-9      0.056347   6.747123e-03
34                        emp_length:10      0.127912   3.913921e-12
35               mths_since_issue_d:<38      1.087614  6.130638e-184
36             mths_since_issue_d:38-39      0.898317  1.050986e-156
37             mths_since_issue_d:40-41      0.800145  4.697765e-131
38             mths_since_issue_d:42-48      0.587456   1.527574e-91
39             mths_since_issue_d:49-52      0.460871   6.019906e-50
40             mths_since_issue_d:53-64      0.210367   4.991590e-13
41             mths_since_issue_d:65-84     -0.050746   8.179398e-02
42                      int_rate:<9.548      1.032490   9.457655e-40
43                int_rate:9.548-12.025      0.620333   7.424903e-44
44                int_rate:12.025-15.74      0.341537   1.290931e-20
45                int_rate:15.74-20.281      0.125881   1.356284e-05
46  mths_since_earliest_cr_line:141-164      0.062932   1.245877e-02
47  mths_since_earliest_cr_line:165-247      0.030811   1.303788e-01
48  mths_since_earliest_cr_line:248-270      0.069679   8.466708e-03
49  mths_since_earliest_cr_line:271-352      0.125008   1.383588e-07
50     mths_since_earliest_cr_line:>352      0.121982   4.641732e-06
51                     inq_last_6mths:0      0.372079   6.162505e-05
52                   inq_last_6mths:1-2      0.223549   1.595883e-02
53                   inq_last_6mths:3-6      0.012637   8.922473e-01
54                   acc_now_delinq:>=1      0.171933   9.842308e-02
55                   annual_inc:20K-30K     -0.117156   5.894980e-03
56                   annual_inc:30K-40K     -0.063623   1.201529e-01
57                   annual_inc:40K-50K      0.044912   2.723427e-01
58                   annual_inc:50K-60K      0.090131   2.935328e-02
59                   annual_inc:60K-70K      0.189258   7.818072e-06
60                   annual_inc:70K-80K      0.245552   1.245807e-08
61                   annual_inc:80K-90K      0.325316   4.410458e-13
62                  annual_inc:90K-100K      0.347899   6.825964e-14
63                 annual_inc:100K-120K      0.406567   9.292864e-19
64                 annual_inc:120K-140K      0.487459   7.700905e-21
65                     annual_inc:>140K      0.428926   2.804408e-19
66                            dti:<=1.4      0.108443   2.089337e-01
67                          dti:1.4-3.5      0.235175   1.316947e-03
68                          dti:3.5-7.7      0.187648   3.202762e-03
69                         dti:7.7-10.5      0.146449   2.087651e-02
70                        dti:10.5-16.1      0.060175   3.276074e-01
71                        dti:16.1-20.3     -0.028908   6.386151e-01
72                        dti:20.3-21.7     -0.037869   5.546622e-01
73                        dti:21.7-22.4     -0.102563   1.308225e-01
74                          dti:22.4-35     -0.132105   3.005946e-02
75       mths_since_last_delinq:Missing      0.132340   1.214278e-02
76          mths_since_last_delinq:4-30      0.146303   6.041604e-03
77         mths_since_last_delinq:31-56      0.197426   2.539671e-04
78          mths_since_last_delinq:>=57      0.161338   3.479902e-03
79       mths_since_last_record:Missing      0.169906   4.517770e-02
80          mths_since_last_record:3-20      0.134628   2.622488e-01
81         mths_since_last_record:21-31      0.208203   7.006554e-02
82         mths_since_last_record:32-80      0.399625   6.903620e-06
83         mths_since_last_record:81-86      0.013924   8.942935e-01
84           mths_since_last_record:>86      0.092544   2.907782e-01

#### Interpreting coefficients of a PD model

Increasing coefficients magnitude - increasing odds of being good
Direct comparisons - betweeen categories from one and the same original independent var only (mutual exclusivity)

In [36]:
import pickle

In [37]:
pickle.dump(reg2, open('pd_model.sav', 'wb'))
# Here we export our model to a 'SAV' file with file name 'pd_model.sav'.

### PD model validation (Test)

In [38]:
# USe dummy variables only excluding the reference variables
loan_data_inputs_test.columns = loan_data_inputs_test.columns.str.replace(' : ', ':')
loan_data_inputs_test.columns = loan_data_inputs_test.columns.str.strip()

# Here, from the dataframe with inputs for testing, we keep the same variables that we used in our final PD model.
inputs_test_with_ref_cat = loan_data_inputs_test.loc[: , ['grade:A',
'grade:B',
'grade:C',
'grade:D',
'grade:E',
'grade:F',
'grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'home_ownership:OWN',
'home_ownership:MORTGAGE',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'addr_state:NM_VA',
'addr_state:NY',
'addr_state:OK_TN_MO_LA_MD_NC',
'addr_state:CA',
'addr_state:UT_KY_AZ_NJ',
'addr_state:AR_MI_PA_OH_MN',
'addr_state:RI_MA_DE_SD_IN',
'addr_state:GA_WA_OR',
'addr_state:WI_MT',
'addr_state:TX',
'addr_state:IL_CT',
'addr_state:KS_SC_CO_VT_AK_MS',
'addr_state:WV_NH_WY_DC_ME_ID',
'verification_status:Not Verified',
'verification_status:Source Verified',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'purpose:credit_card',
'purpose:debt_consolidation',
'purpose:oth__med__vacation',
'purpose:major_purch__car__home_impr',
'initial_list_status:f',
'initial_list_status:w',
'term:36',
'term:60',
'emp_length:0',
'emp_length:1',
'emp_length:2-4',
'emp_length:5-6',
'emp_length:7-9',
'emp_length:10',
'mths_since_issue_d:<38',
'mths_since_issue_d:38-39',
'mths_since_issue_d:40-41',
'mths_since_issue_d:42-48',
'mths_since_issue_d:49-52',
'mths_since_issue_d:53-64',
'mths_since_issue_d:65-84',
'mths_since_issue_d:>84',
'int_rate:<9.548',
'int_rate:9.548-12.025',
'int_rate:12.025-15.74',
'int_rate:15.74-20.281',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'mths_since_earliest_cr_line:141-164',
'mths_since_earliest_cr_line:165-247',
'mths_since_earliest_cr_line:248-270',
'mths_since_earliest_cr_line:271-352',
'mths_since_earliest_cr_line:>352',
'inq_last_6mths:0',
'inq_last_6mths:1-2',
'inq_last_6mths:3-6',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'acc_now_delinq:>=1',
'annual_inc:<20K',
'annual_inc:20K-30K',
'annual_inc:30K-40K',
'annual_inc:40K-50K',
'annual_inc:50K-60K',
'annual_inc:60K-70K',
'annual_inc:70K-80K',
'annual_inc:80K-90K',
'annual_inc:90K-100K',
'annual_inc:100K-120K',
'annual_inc:120K-140K',
'annual_inc:>140K',
'dti:<=1.4',
'dti:1.4-3.5',
'dti:3.5-7.7',
'dti:7.7-10.5',
'dti:10.5-16.1',
'dti:16.1-20.3',
'dti:20.3-21.7',
'dti:21.7-22.4',
'dti:22.4-35',
'dti:>35',
'mths_since_last_delinq:Missing',
'mths_since_last_delinq:0-3',
'mths_since_last_delinq:4-30',
'mths_since_last_delinq:31-56',
'mths_since_last_delinq:>=57',
'mths_since_last_record:Missing',
'mths_since_last_record:0-2',
'mths_since_last_record:3-20',
'mths_since_last_record:21-31',
'mths_since_last_record:32-80',
'mths_since_last_record:81-86',
'mths_since_last_record:>86',
]]

In [39]:
# And here, in the list below, we keep the variable names for the reference categories,
# only for the variables we used in our final PD model.
ref_categories = ['grade:G',
'home_ownership:RENT_OTHER_NONE_ANY',
'addr_state:ND_NE_IA_NV_FL_HI_AL',
'verification_status:Verified',
'purpose:educ__sm_b__wedd__ren_en__mov__house',
'initial_list_status:f',
'term:60',
'emp_length:0',
'mths_since_issue_d:>84',
'int_rate:>20.281',
'mths_since_earliest_cr_line:<140',
'inq_last_6mths:>6',
'acc_now_delinq:0',
'annual_inc:<20K',
'dti:>35',
'mths_since_last_delinq:0-3',
'mths_since_last_record:0-2']

In [40]:
inputs_test = inputs_test_with_ref_cat.drop(ref_categories, axis = 1)
inputs_test.head()

,grade:A,grade:B,grade:C,grade:D,grade:E,grade:F,home_ownership:OWN,home_ownership:MORTGAGE,addr_state:NM_VA,addr_state:NY,...,mths_since_last_delinq:Missing,mths_since_last_delinq:4-30,mths_since_last_delinq:31-56,mths_since_last_delinq:>=57,mths_since_last_record:Missing,mths_since_last_record:3-20,mths_since_last_record:21-31,mths_since_last_record:32-80,mths_since_last_record:81-86,mths_since_last_record:>86
395346,0,0,1,0,0,0,1,0,0,0,...,1,0,0,0,0,0,0,1,0,0
376583,1,0,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
297790,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
47347,0,1,0,0,0,0,0,0,0,0,...,1,0,0,0,1,0,0,0,0,0
446772,0,0,0,1,0,0,0,1,0,0,...,1,0,0,0,1,0,0,0,0,0

In [41]:
y_hat_test = reg2.model.predict(inputs_test)
# Calculates the predicted values for the dependent variable (targets)
# based on the values of the independent variables (inputs) supplied as an argument.

In [42]:
y_hat_test
# This is an array of predicted discrete classess (in this case, 0s and 1s).

array([1, 1, 1, ..., 1, 1, 1], shape=(93257,))

In [43]:
y_hat_test_proba = reg2.model.predict_proba(inputs_test)
# Calculates the predicted probability values for the dependent variable (targets)
# based on the values of the independent variables (inputs) supplied as an argument.

In [44]:
y_hat_test_proba
# This is an array of arrays of predicted class probabilities for all classes.
# In this case, the first value of every sub-array is the probability for the observation to belong to the first class, i.e. 0,
# and the second value is the probability for the observation to belong to the first class, i.e. 1.

array([[0.10837957, 0.89162043],
       [0.02591285, 0.97408715],
       [0.0937232 , 0.9062768 ],
       ...,
       [0.20885116, 0.79114884],
       [0.06966508, 0.93033492],
       [0.1566464 , 0.8433536 ]], shape=(93257, 2))

In [45]:
y_hat_test_proba[:][:,1]
# Here we take all the arrays in the array, and from each array, we take all rows, and only the element with index 1,
# that is, the second element.
# In other words, we take only the probabilities for being 1.

array([0.89162043, 0.97408715, 0.9062768 , ..., 0.79114884, 0.93033492,
       0.8433536 ], shape=(93257,))

In [46]:
y_hat_test_proba = y_hat_test_proba[: ][: , 1]
# We store these probabilities in a variable.

In [47]:
y_hat_test_proba
# This variable contains an array of probabilities of being 1.

array([0.89162043, 0.97408715, 0.9062768 , ..., 0.79114884, 0.93033492,
       0.8433536 ], shape=(93257,))

In [49]:
loan_data_target_test_temp = loan_data_target_test

In [50]:
loan_data_target_test_temp.reset_index(drop = True, inplace = True)
# We reset the index of a dataframe.

In [51]:
df_actual_predicted_probs = pd.concat([loan_data_target_test_temp, pd.DataFrame(y_hat_test_proba)], axis = 1)
# Concatenates two dataframes.

In [52]:
df_actual_predicted_probs.shape

(93257, 2)

In [53]:
df_actual_predicted_probs.columns = ['loan_data_target_test', 'y_hat_test_proba']

In [54]:
df_actual_predicted_probs.index = loan_data_inputs_test.index
# Makes the index of one dataframe equal to the index of another dataframe.

In [55]:
df_actual_predicted_probs.head()

        loan_data_target_test  y_hat_test_proba
395346                      1          0.891620
376583                      1          0.974087
297790                      1          0.906277
47347                       1          0.907128
446772                      0          0.888159